WRONG-
1. preprocessing & cleaning(feature engineering)
2. bow/tfidf - sentence into vectors(feature extraction)
3. train-test split
4. train ml model 

RIGHT- <br />
(preventing data leakage)
1. preprocessing & cleaning(feature engineering)
2. train-test split
3. bow/tfidf - sentence into vectors(feature extraction)
4. train ml model 

# 1. Loading dataset

In [ ]:
import pandas as pd
messages = pd.read_csv('sms_spam_db.txt', sep='\t', names=["label", "message"])

In [3]:
messages

label                                            message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham               Will ü b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

# 2. Data cleaning and preprocessing

In [4]:
import re
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\hp\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [5]:
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [6]:
corpus = []
for i in range(0, len(messages)):
    review = re.sub('[^a-zA-z]', ' ', messages['message'][i])
    review = review.lower()
    review = review.split()
    review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)

In [7]:
corpus

['go jurong point crazi avail bugi n great world la e buffet cine got amor wat',
 'ok lar joke wif u oni',
 'free entri wkli comp win fa cup final tkt st may text fa receiv entri question std txt rate c appli',
 'u dun say earli hor u c alreadi say',
 'nah think goe usf live around though',
 'freemsg hey darl week word back like fun still tb ok xxx std chg send rcv',
 'even brother like speak treat like aid patent',
 'per request mell mell oru minnaminungint nurungu vettam set callertun caller press copi friend callertun',
 'winner valu network custom select receivea prize reward claim call claim code kl valid hour',
 'mobil month u r entitl updat latest colour mobil camera free call mobil updat co free',
 'gonna home soon want talk stuff anymor tonight k cri enough today',
 'six chanc win cash pound txt csh send cost p day day tsandc appli repli hl info',
 'urgent week free membership prize jackpot txt word claim c www dbuk net lccltd pobox ldnw rw',
 'search right word thank breather

In [8]:
## output/dependent features - label
y = pd.get_dummies(messages['label'])
y = y.iloc[:,1].values ## taking only spam col

# 3. Train-test split (BoW)

In [9]:
## train-test split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(corpus, y, test_size=0.20)

# 4. Converting text to numerical features (BoW)

In [10]:
## creating BOW model
from sklearn.feature_extraction.text import CountVectorizer
## for binary BOW enabling binary=True
cv = CountVectorizer(max_features=2500, ngram_range=(1,2))

In [11]:
len(X_train), len(y_train)

(4457, 4457)

In [12]:
## independent features
X_train = cv.fit_transform(X_train).toarray()
X_test = cv.transform(X_test).toarray()

In [13]:
import numpy as np
np.set_printoptions(edgeitems=30, linewidth=100000, formatter=dict(float=lambda x: "%.3g" % x))
X_train

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0

In [14]:
cv.vocabulary_

{'ok': 1474,
 'good': 819,
 'later': 1107,
 'come': 385,
 'find': 689,
 'lucki': 1224,
 'told': 2163,
 'go': 794,
 'earlier': 582,
 'pple': 1622,
 'take': 2060,
 'finish': 695,
 'requir': 1737,
 'mth': 1370,
 'half': 892,
 'price': 1636,
 'orang': 1506,
 'line': 1158,
 'rental': 1728,
 'latest': 1110,
 'camera': 280,
 'phone': 1559,
 'free': 721,
 'call': 245,
 'updat': 2245,
 'stoptxt': 2007,
 'mth half': 1372,
 'half price': 894,
 'price orang': 1638,
 'orang line': 1507,
 'line rental': 1160,
 'latest camera': 1111,
 'camera phone': 283,
 'phone free': 1561,
 'free phone': 730,
 'txt': 2213,
 'rememb': 1724,
 'want': 2332,
 'talk': 2065,
 'want talk': 2341,
 'remind': 1725,
 'get': 769,
 'pound': 1620,
 'credit': 451,
 'detail': 523,
 'great': 850,
 'offer': 1464,
 'pl': 1576,
 'repli': 1729,
 'text': 2094,
 'valid': 2291,
 'name': 1388,
 'hous': 967,
 'free call': 723,
 'pl repli': 1582,
 'hi': 928,
 'kind': 1076,
 'feel': 673,
 'tomo': 2164,
 'mind': 1304,
 'wow': 2447,
 'never': 

## 5. Training ML model (BoW)

In [15]:
## classification using ml algo
from sklearn.naive_bayes import MultinomialNB
spam_detect_model = MultinomialNB().fit(X_train, y_train)
spam_detect_model

MultinomialNB()

## 6. Predicting and evaluating (BoW)

In [16]:
y_pred = spam_detect_model.predict(X_test)
y_pred

array([False,  True, False, False, False, False, False, False,  True, False,  True, False, False, False, False, False, False, False, False, False, False, False, False, False,  True,  True, False, False, False, False, ...,  True, False, False, False, False, False,  True, False,  True,  True, False, False, False, False, False, False, False, False, False, False, False,  True, False, False, False, False, False, False, False, False])

In [17]:
from sklearn.metrics import accuracy_score, classification_report
accuracy_score(y_test, y_pred)

0.9847533632286996

In [18]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

       False       0.99      0.99      0.99       956
        True       0.96      0.93      0.95       159

    accuracy                           0.98      1115
   macro avg       0.97      0.96      0.97      1115
weighted avg       0.98      0.98      0.98      1115



## 3.1 Train-test split (Tfidf)

In [19]:
## train-test split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(corpus, y, test_size=0.20)

## 4.1 Converting text to numerical features (Tfidf)

In [20]:
from sklearn.feature_extraction.text import TfidfVectorizer
tv = TfidfVectorizer(max_features=2500, ngram_range=(1,2))
X_train = tv.fit_transform(X_train).toarray()
X_test = tv.transform(X_test).toarray()

In [21]:
X_train

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0

In [22]:
tv.vocabulary_

{'ok': 1486,
 'darlin': 472,
 'worri': 2433,
 'much': 1386,
 'film': 673,
 'stuff': 2018,
 'mate': 1266,
 'call': 237,
 'xx': 2466,
 'pleas': 1604,
 'give': 786,
 'pick': 1578,
 'tuesday': 2197,
 'even': 613,
 'sen': 1842,
 'told': 2155,
 'go': 795,
 'join': 1065,
 'uncl': 2224,
 'cbe': 303,
 'cook': 410,
 'dinner': 521,
 'dont': 539,
 'send': 1843,
 'plu': 1609,
 'mode': 1348,
 'carlo': 291,
 'took': 2166,
 'leav': 1141,
 'minut': 1315,
 'aight': 36,
 'still': 1997,
 'want': 2333,
 'get': 766,
 'money': 1356,
 'want get': 2335,
 'secret': 1823,
 'admir': 18,
 'look': 1198,
 'make': 1245,
 'contact': 398,
 'find': 676,
 'reveal': 1761,
 'think': 2108,
 'ur': 2238,
 'special': 1964,
 'ppm': 1642,
 'secret admir': 1824,
 'admir look': 19,
 'look make': 1200,
 'make contact': 1246,
 'contact find': 401,
 'find reveal': 679,
 'reveal think': 1762,
 'think ur': 2111,
 'ur special': 2259,
 'special call': 1966,
 'cool': 411,
 'like': 1163,
 'hous': 973,
 'sent': 1853,
 'custom': 456,
 'servi

## 5.1 Training ML model (Tfidf)

In [23]:
from sklearn.naive_bayes import MultinomialNB
spam_tfidf_model = MultinomialNB().fit(X_train, y_train)
spam_tfidf_model 

MultinomialNB()

## 6.1 Predicting and evaluating (Tfidf)

In [24]:
## predictions
y_pred = spam_tfidf_model.predict(X_test)

In [25]:
score = accuracy_score(y_test, y_pred)
print(score)

0.9713004484304932


In [26]:
from sklearn.metrics import accuracy_score, classification_report
print(classification_report(y_pred, y_test))

              precision    recall  f1-score   support

       False       1.00      0.97      0.98       990
        True       0.80      0.98      0.88       125

    accuracy                           0.97      1115
   macro avg       0.90      0.98      0.93      1115
weighted avg       0.98      0.97      0.97      1115



## 7. Testing on new messages

In [36]:
def preprocess_text(text):
    ps = PorterStemmer()
    text = re.sub('[^a-zA-Z]', ' ', text)  
    text = text.lower().split() 
    text = [ps.stem(word) for word in text if word not in stopwords.words('english')]
    return ' '.join(text) 

input_text = "Congrats! You have cleared the interview. Take the next steps to complete recruitmemt process"
processed_text = preprocess_text(input_text)
input_features = cv.transform([processed_text]).toarray()  
prediction = spam_detect_model.predict(input_features) 
print("Spam" if prediction[0] == 1 else "Ham")

Ham


In [ ]:
input_text = "Give me us your bank details. Limites"
processed_text = preprocess_text(input_text)
input_features = cv.transform([processed_text]).toarray()  
prediction = spam_detect_model.predict(input_features) 
print("Spam" if prediction[0] == 1 else "Ham")


Ham


In [ ]:
test_messages = [
    "Congratulations! You have won a free lottery. Click here to claim now.",  
    "Hey, are we still meeting for lunch today?",  
    "URGENT! Your account has been compromised. Reset your password immediately.",  
    "Reminder: Your doctor’s appointment is scheduled for tomorrow at 10 AM.",  
    "You’ve been selected for a special offer! Call now to claim your reward.",  
    "Can you send me the notes from today’s lecture?",  
    "Win a brand new iPhone! Limited time offer. Reply YES to participate.", 
    "Don't forget to submit the assignment by 5 PM.",  
    "Get your credit card limit increased instantly! Click the link below.",  
    "Meeting rescheduled to 3 PM. Let me know if that works for you.", 
]

for msg in test_messages:
    processed_text = preprocess_text(msg)  
    input_features = cv.transform([processed_text]).toarray()  
    prediction = spam_detect_model.predict(input_features) 
    
    print(f"Message: \"{msg}\"")
    print("Prediction:", "Spam" if prediction[0] == 1 else "Ham")
    print("-" *10)  


Message: "Congratulations! You have won a free lottery. Click here to claim now."
Prediction: Spam
----------
Message: "Hey, are we still meeting for lunch today?"
Prediction: Ham
----------
Message: "URGENT! Your account has been compromised. Reset your password immediately."
Prediction: Spam
----------
Message: "Reminder: Your doctor’s appointment is scheduled for tomorrow at 10 AM."
Prediction: Ham
----------
Message: "You’ve been selected for a special offer! Call now to claim your reward."
Prediction: Spam
----------
Message: "Can you send me the notes from today’s lecture?"
Prediction: Ham
----------
Message: "Win a brand new iPhone! Limited time offer. Reply YES to participate."
Prediction: Spam
----------
Message: "Don't forget to submit the assignment by 5 PM."
Prediction: Ham
----------
Message: "Get your credit card limit increased instantly! Click the link below."
Prediction: Spam
----------
Message: "Meeting rescheduled to 3 PM. Let me know if that works for you."
Predicti